### ISSUE TITLE
y-cruncher is not open source

### ISSUE THREAD

**Issue by fffffgggg54** [Mysticial/y-cruncher-GUI#3]
y-cruncher is not open source, which could potentially slow work. @Mysticial Is there a reason y-cruncher is not open source?

**Comment by Mysticial** [comment]
The benchmark validation code cannot be open-sourced since it's inherently security through obfuscation. So open-sourcing it will render it completely useless and will invalidate HWBOT submissions.

Much of the mathematical and computational code is proprietary and also cannot be open-sourced.

On the other hand, there's nothing sensitive about the UI code. So that can be open-sourced. However, it won't be compilable due to the numerous dependencies on the stuff above.

**Comment by fffffgggg54** [comment]
Please correct me if I'm wrong, all the computation and validation code is closed source because of various reasons but all the code to run and use the closed source code is open source.

**Comment by Mysticial** [comment]
Close. The "code to run and use the closed source code" *can* be open-sourced, but it currently *isn't*.

The current UI code is not well separated from the internal code due to years of poor (non-existent) planning. So a significant amount of refactoring will be needed to make that separation and place an abstraction layer in between.

I haven't started doing this yet since I need a better idea of what direction the GUI would be headed before I can design that abstraction layer.

**Comment by fffffgggg54** [comment]
I feel that we can work on the GUI to the point where we have a solid idea of how it will work and interface with the rest of the program and then rework the internals.
