### ISSUE TITLE
Secondary interface or graphical equivalent of the current CLI?

### ISSUE THREAD

**Issue by fffffgggg54** [Mysticial/y-cruncher-GUI#4]
Should this new proposed GUI be 1), a secondary way to interface with y-cruncher, as in it launches the CLI and interfaces with it or 2), should the new GUI be able to run independently of the current CLI and be able to do all the current functions of the CLI?
1) - PROS - no need to redo structure, easier to implement
      CONS - reliance on CLI, presumably less freedom for the new GUI in terms of design possibilities
2) - PROS - free of CLI, more freedom for the data fields, the redone structure allows for easier improvements in the future
       CONS - more time and effort needed, potentially taking away large chunks of time otherwise spent on stable release development.

**Comment by Mysticial** [comment]
#2. I think the GUI should not use the CLI at all except to tell y-cruncher to start in a "slave mode".

I tried the CLI-only approach with the HWBot Submitter last year and it simply doesn't work well since there's no way for y-cruncher to pass any information back to the GUI. So it's impossible to implement the Custom Compute menu with only CLI since the GUI cannot receive anything back from y-cruncher (such as memory calculations, parameter auto-correction, warnings, etc...). Likewise, the GUI can't display the progress and status updates without capturing stdout.

So what I'm thinking of right now is that the GUI binary runs something like, "y-cruncher slave port:30000" as a background process. This starts y-cruncher in "slave mode" where all interactions (writes to stdout and reads from stdin) are replaced with an IPC or network protocol to connect with the GUI. This will be possible after the UI separation+API refactor I [mentioned in the other thread](https://github.com/Mysticial/y-cruncher-GUI/issues/3).

**Comment by fffffgggg54** [comment]
I don't understand the last 2 paragraphs, however, what I understand is that a GUI will be run, which will start y-cruncher and run the desired computation.
